"""add rollback status to releases

Revision ID: 178094a0171f
Revises: 8bd5775d1627
Create Date: 2026-10-04 11:19:47.309969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178094a0171f'
down_revision: Union[str, Sequence[str], None] = '8bd5775d1627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('rollback_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'rollback_status')
    # ### end Alembic commands ###
